### ISSUE TITLE
Index, Event #, and Cell_Index

### ISSUE THREAD

**Issue by FerranC96** [TAPE-Lab/CyTOF_DataAnalysis#44]

**Comment by FerranC96** [comment]
> Basically the auxiliary script for preprocessing FCS files now assigns cell-index by renaming the column 'Event #' to 'Cell_Index'
<sub>[View in Slack](https://tapelab.slack.com/archives/G011PACQ1A8/p1594203092008300)</sub>

**Comment by FerranC96** [comment]
> However, the 'Even #' is inherited from Cytobank, which means, the pre-cytobank fcs files don't have that column :grimacing:
<sub>[View in Slack](https://tapelab.slack.com/archives/G011PACQ1A8/p1594203149009700)</sub>

**Comment by FerranC96** [comment]
> and when it comes to UMAP, the concatenation/downsample procedure is dependent on the 'Cell_Index' column, therefore throwing an error message
<sub>[View in Slack](https://tapelab.slack.com/archives/G011PACQ1A8/p1594203245011100)</sub>

**Comment by qinxiao1990** [comment]
The problem could be solved by using the data frame index in the raw data to assign 'Cell_Index'

**Comment by FerranC96** [comment]
Solved
